name: Update numbers

on:
    workflow_dispatch:
    schedule:
      - cron:  '0 0 1 * *' # run on the first of each month

jobs:
    monthly-update:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: 14
                  cache: yarn

            - name: Set up Cloud SDK
              uses: google-github-actions/setup-gcloud@master
              with:
                project_id: ${{ secrets.GCP_PROJECT_ID }}
                service_account_key: ${{ secrets.GCP_SA_KEY }}
                export_default_credentials: true

            - run: yarn install

            - run: yarn run all # "fetch", "analyze", and "build"
              with:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: Evaluate all artifacts for the current month
