name: Update numbers

# TODO change to monthly schedule
on:
    workflow_dispatch:
    # schedule:
    #   - cron:  '0 */6 * * *'

jobs:
    run-test:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: 14
                  cache: yarn

            - run: yarn install

            - run: yarn run all # "fetch", "analyze", and "build"

            # TODO replace with GH action
            - name: Commit changes if required
              if: ${{ success() }}
              run: |
                  git config --global user.email "marius.obert@sap.com"
                  git config --global user.name "D056949"
                  git commit -m 'Evaluate all artifacts for the current month' || exit 0
                  git push
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            # - uses: stefanzweifel/git-auto-commit-action@v4
            #   with:
            #     commit_message: Evaluate all artifacts for the current month
