name: Update GitHub Pages

on:
    push

jobs:
    build-gh-pages:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: 14
                  cache: yarn

            - run: yarn install

            - run: yarn run build

            - uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: "Chore: Build webapp"
