name: Update Github Data

on:
    workflow_dispatch:
    schedule:
      - cron:  '0 0 1 * *' # run on the first of each month

jobs:
    monthly-update:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: 14
                  cache: yarn

            - run: yarn install

            - run: yarn run update-gh # "fetch", "analyze", and "build"

            - uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: Update GitHub Data
